-- Fouad CLI platform schema for project icpegitgbqdkuhgfqevh.
-- Declarative schema: review and generate a migration before remote application.

create table if not exists public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique check (username ~ '^[A-Za-z0-9_]{3,32}$'),
  display_name text not null check (char_length(display_name) between 1 and 80),
  avatar_url text,
  locale text not null default 'en' check (locale in ('en','ar')),
  status text not null default 'active' check (status in ('active','disabled','deleted')),
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz
);
create table if not exists public.user_roles (user_id uuid primary key references auth.users(id) on delete cascade, role text not null default 'user' check(role in ('user','admin')), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.plans (id text primary key check(id in ('free','pro','team','enterprise')), name text not null, enabled boolean not null default false, limits jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
insert into public.plans(id,name,enabled) values('free','Free',true),('pro','Pro',false),('team','Team',false),('enterprise','Enterprise',false) on conflict(id) do nothing;
create table if not exists public.user_entitlements (user_id uuid primary key references auth.users(id) on delete cascade, plan_id text not null default 'free' references public.plans(id), overrides jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.cli_devices (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, name text not null check(char_length(name) between 1 and 120), platform text not null, device_fingerprint_hash text not null, last_seen_at timestamptz, revoked_at timestamptz, created_at timestamptz not null default now(), unique(user_id,device_fingerprint_hash));
create index if not exists cli_devices_user_created_idx on public.cli_devices(user_id,created_at desc);
create table if not exists public.cli_auth_requests (id uuid primary key default gen_random_uuid(), device_code_hash text not null unique, user_code_hash text not null unique, state_hash text not null, pkce_challenge text not null, device_name text not null, platform text not null, user_id uuid references auth.users(id) on delete cascade, status text not null default 'pending' check(status in ('pending','approved','denied','expired','consumed')), expires_at timestamptz not null, poll_interval_seconds integer not null default 5 check(poll_interval_seconds between 3 and 30), last_polled_at timestamptz, created_at timestamptz not null default now(), consumed_at timestamptz);
create index if not exists cli_auth_requests_expiry_idx on public.cli_auth_requests(expires_at) where status='pending';
create table if not exists public.cli_sessions (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, device_id uuid not null references public.cli_devices(id) on delete cascade, token_family_id uuid not null default gen_random_uuid(), expires_at timestamptz not null, revoked_at timestamptz, created_at timestamptz not null default now(), last_seen_at timestamptz);
create index if not exists cli_sessions_user_idx on public.cli_sessions(user_id,created_at desc);
create index if not exists cli_sessions_device_idx on public.cli_sessions(device_id);
create table if not exists public.cli_refresh_tokens (id uuid primary key default gen_random_uuid(), session_id uuid not null references public.cli_sessions(id) on delete cascade, token_hash text not null unique, parent_token_hash text, expires_at timestamptz not null, used_at timestamptz, revoked_at timestamptz, created_at timestamptz not null default now());
create index if not exists cli_refresh_tokens_session_idx on public.cli_refresh_tokens(session_id,created_at desc);
create table if not exists public.security_events (id bigint generated always as identity primary key, user_id uuid references auth.users(id) on delete set null, event_type text not null, severity text not null check(severity in ('info','warning','critical')), request_id text, ip_hash text, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
create index if not exists security_events_user_created_idx on public.security_events(user_id,created_at desc);
create table if not exists public.admin_audit_logs (id bigint generated always as identity primary key, admin_user_id uuid not null references auth.users(id) on delete restrict, action text not null, target_type text not null, target_id text, request_id text, before_state jsonb, after_state jsonb, created_at timestamptz not null default now());
create index if not exists admin_audit_logs_admin_created_idx on public.admin_audit_logs(admin_user_id,created_at desc);
create table if not exists public.ai_providers (id uuid primary key default gen_random_uuid(), slug text not null unique, name text not null, adapter text not null, base_url text, secret_reference text, enabled boolean not null default false, priority integer not null default 100, timeout_ms integer not null default 30000 check(timeout_ms between 1000 and 120000), retry_policy jsonb not null default '{}'::jsonb, capabilities jsonb not null default '{}'::jsonb, maintenance boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.ai_models (id uuid primary key default gen_random_uuid(), provider_id uuid not null references public.ai_providers(id) on delete cascade, model_id text not null, display_name text not null, aliases text[] not null default '{}', enabled boolean not null default false, capabilities jsonb not null default '{}'::jsonb, limits jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(provider_id,model_id));
create index if not exists ai_models_provider_idx on public.ai_models(provider_id,enabled);
create table if not exists public.provider_health_events (id bigint generated always as identity primary key, provider_id uuid not null references public.ai_providers(id) on delete cascade, status text not null check(status in ('healthy','degraded','failed')), latency_ms integer, error_code text, created_at timestamptz not null default now());
create index if not exists provider_health_provider_created_idx on public.provider_health_events(provider_id,created_at desc);
create table if not exists public.usage_records (id bigint generated always as identity primary key, user_id uuid not null references auth.users(id) on delete cascade, provider_id uuid references public.ai_providers(id) on delete set null, model_id uuid references public.ai_models(id) on delete set null, request_id text not null unique, input_tokens bigint not null default 0 check(input_tokens>=0), output_tokens bigint not null default 0 check(output_tokens>=0), created_at timestamptz not null default now());
create index if not exists usage_records_user_created_idx on public.usage_records(user_id,created_at desc);
create table if not exists public.feature_flags (key text primary key, enabled boolean not null default false, audience jsonb not null default '{}'::jsonb, description text not null default '', updated_at timestamptz not null default now());
create table if not exists public.site_settings (key text primary key, value jsonb not null, is_public boolean not null default false, updated_at timestamptz not null default now());
create table if not exists public.site_content (id uuid primary key default gen_random_uuid(), content_key text not null, locale text not null check(locale in ('en','ar')), status text not null default 'draft' check(status in ('draft','published','archived')), value jsonb not null, published_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(content_key,locale,status));
create table if not exists public.site_revisions (id uuid primary key default gen_random_uuid(), content_id uuid not null references public.site_content(id) on delete cascade, revision integer not null, value jsonb not null, created_by uuid not null references auth.users(id) on delete restrict, created_at timestamptz not null default now(), unique(content_id,revision));
create index if not exists site_revisions_content_idx on public.site_revisions(content_id,revision desc);
create table if not exists public.releases (id uuid primary key default gen_random_uuid(), version text not null unique, channel text not null default 'stable', published boolean not null default false, notes_markdown text not null default '', artifacts jsonb not null default '[]'::jsonb, published_at timestamptz, created_at timestamptz not null default now());

alter table public.profiles enable row level security; alter table public.user_roles enable row level security; alter table public.plans enable row level security; alter table public.user_entitlements enable row level security; alter table public.cli_devices enable row level security; alter table public.cli_auth_requests enable row level security; alter table public.cli_sessions enable row level security; alter table public.cli_refresh_tokens enable row level security; alter table public.security_events enable row level security; alter table public.admin_audit_logs enable row level security; alter table public.ai_providers enable row level security; alter table public.ai_models enable row level security; alter table public.provider_health_events enable row level security; alter table public.usage_records enable row level security; alter table public.feature_flags enable row level security; alter table public.site_settings enable row level security; alter table public.site_content enable row level security; alter table public.site_revisions enable row level security; alter table public.releases enable row level security;

drop policy if exists profiles_owner_select on public.profiles; create policy profiles_owner_select on public.profiles for select to authenticated using((select auth.uid())=user_id);
drop policy if exists profiles_owner_update on public.profiles; create policy profiles_owner_update on public.profiles for update to authenticated using((select auth.uid())=user_id) with check((select auth.uid())=user_id);
drop policy if exists user_roles_owner_select on public.user_roles; create policy user_roles_owner_select on public.user_roles for select to authenticated using((select auth.uid())=user_id);
drop policy if exists entitlements_owner_select on public.user_entitlements; create policy entitlements_owner_select on public.user_entitlements for select to authenticated using((select auth.uid())=user_id);
drop policy if exists devices_owner_select on public.cli_devices; create policy devices_owner_select on public.cli_devices for select to authenticated using((select auth.uid())=user_id);
drop policy if exists sessions_owner_select on public.cli_sessions; create policy sessions_owner_select on public.cli_sessions for select to authenticated using((select auth.uid())=user_id);
drop policy if exists usage_owner_select on public.usage_records; create policy usage_owner_select on public.usage_records for select to authenticated using((select auth.uid())=user_id);
drop policy if exists plans_public_select on public.plans; create policy plans_public_select on public.plans for select to anon,authenticated using(enabled=true);
drop policy if exists content_public_select on public.site_content; create policy content_public_select on public.site_content for select to anon,authenticated using(status='published');
drop policy if exists releases_public_select on public.releases; create policy releases_public_select on public.releases for select to anon,authenticated using(published=true);

revoke all on public.profiles,public.user_roles,public.plans,public.user_entitlements,public.cli_devices,public.cli_auth_requests,public.cli_sessions,public.cli_refresh_tokens,public.security_events,public.admin_audit_logs,public.ai_providers,public.ai_models,public.provider_health_events,public.usage_records,public.feature_flags,public.site_settings,public.site_content,public.site_revisions,public.releases from anon,authenticated;
grant select on public.plans,public.site_content,public.releases to anon,authenticated;
grant select on public.profiles,public.user_roles,public.user_entitlements,public.cli_devices,public.cli_sessions,public.usage_records to authenticated;
grant update(username,display_name,avatar_url,locale,updated_at) on public.profiles to authenticated;
